/**
 * Safe error helper for server actions & API routes.
 *
 * Appwrite (and other backend SDK) errors often embed internal details —
 * collection IDs, endpoint URLs, query strings — that must **never** be
 * returned to the client.
 *
 * `safeError(err, fallback)` logs the real error server-side and returns
 * only the `fallback` string.  If the error is a well-known user-facing
 * message (e.g. "Email and password are required") you can allowlist it
 * via the third `allowlist` parameter.
 */

import { logger } from '@/lib/logger';

/**
 * Error messages that are safe to surface as-is because they were
 * generated by our own validation logic, not by a downstream SDK.
 */
const SAFE_PREFIXES = [
  'Forbidden',
  'Access denied',
  'Not found',
  'Unauthorized',
  'Too many',
  'Invalid',
  'required',
  'already exists',
  'Session expired',
] as const;

function isSafeMessage(msg: string): boolean {
  return SAFE_PREFIXES.some(
    (prefix) => msg.startsWith(prefix) || msg.toLowerCase().startsWith(prefix.toLowerCase())
  );
}

/**
 * Log the real error and return a safe client-facing message.
 *
 * @param err      — The caught error (unknown)
 * @param fallback — Generic message to show the user, e.g. "Failed to save"
 * @returns        — Either the original message (if safe) or the fallback
 */
export function safeError(err: unknown, fallback: string): string {
  const raw =
    err instanceof Error
      ? err.message
      : typeof err === 'string'
        ? err
        : 'Unknown error';

  // Always log the real error server-side for debugging
  logger.error(fallback, { error: raw });

  // If the message was generated by our own code, surface it
  if (isSafeMessage(raw)) {
    return raw;
  }

  // Otherwise return the generic fallback
  return fallback;
}
